<?php
// config/lang_th.php
// Translation array for Thai language

return [
    'home' => 'หน้าแรก',
    'ita' => 'ข้อมูล ITA Online',
    'information_system' => 'ระบบสารสนเทศ',
    'sgs' => 'ระบบ SGS (วัดผลประเมินผล)',
    'dmc' => 'ระบบ DMC (ข้อมูลนักเรียน)',
    'obec' => 'เว็บไซต์ สพฐ.',
    'emis' => 'ระบบ EMIS สารสนเทศ',
    'gpa' => 'ระบบ GPA (ผลการเรียน)',
    'admin_panel' => 'Login',
    'admin_dashboard' => 'ระบบแอดมิน',
    'logout' => 'ออกจากระบบ',
    'welcome_school' => 'ยินดีต้อนรับสู่สถานศึกษาของเรา',
    'hero_title' => 'ขับเคลื่อนอนาคตด้วย <br> <span class="text-gradient-primary">นวัตกรรมและเทคโนโลยี</span>',
    'hero_desc' => 'เรามุ่งส่งเสริมทักษะวิชาการ คุณลักษณะอันพึงประสงค์ และการประยุกต์ใช้เทคโนโลยีสมัยใหม่ พร้อมสร้างความเชื่อมั่นผ่านระบบการจัดการโรงเรียนโปร่งใส ตรวจสอบได้ ITA Online',
    'check_ita' => 'ตรวจสอบ ITA Online',
    'read_news' => 'อ่านข่าวสารประชาสัมพันธ์',
    'slider1_title' => 'แหล่งเรียนรู้นวัตกรรมและวิทยาการคำนวณ',
    'slider1_desc' => 'ห้องปฏิบัติการคอมพิวเตอร์และเทคโนโลยีหุ่นยนต์ สำหรับฝึกทักษะการวิเคราะห์และพัฒนานวัตกรรม',
    'slider2_title' => 'มุ่งพัฒนาคุณภาพการศึกษาสู่สากล',
    'slider2_desc' => 'หลักสูตรส่งเสริมภาษาและการคิดวิเคราะห์ เพื่อปูทางสู่ความสำเร็จในยุคเศรษฐกิจสร้างสรรค์',
    'ita_status' => 'ความโปร่งใสของหน่วยงาน (ITA Online)',
    'ita_status_desc' => 'รายงานผลการดำเนินการและเผยแพร่ข้อมูลผู้รับบริการสาธารณะ ตามตัวชี้วัดความโปร่งใส O1 - O43 ประจำปีงบประมาณปัจจุบัน',
    'published_stats' => 'เผยแพร่แล้ว %d จาก %d ตัวชี้วัด',
    'view_ita_table' => 'ดูตารางตัวชี้วัด',
    'external_portals' => 'ระบบงานและสารสนเทศภายนอก',
    'external_portals_desc' => 'ทางลัดเชื่อมต่อระบบงานเพื่อการบริหารจัดการและการอำนวยความสะดวกครู นักเรียน และบุคลากร',
    'news_section_title' => 'ข่าวสารประชาสัมพันธ์',
    'news_section_desc' => 'กิจกรรม ข่าวประกาศ และประชาสัมพันธ์ล่าสุดจากทางโรงเรียน',
    'school_journal' => 'วารสารโรงเรียน',
    'all' => 'ทั้งหมด',
    'announcement' => 'ประกาศ',
    'activity' => 'ภาพข่าวกิจกรรม',
    'general' => 'ประชาสัมพันธ์',
    'procurement' => 'จัดซื้อจัดจ้าง',
    'no_news' => 'ยังไม่มีรายการข่าวประชาสัมพันธ์เผยแพร่ในขณะนี้',
    'read_more' => 'อ่านต่อ',
    'by' => 'โดย',
    'pdpa_title' => 'เราใส่ใจในความเป็นส่วนตัวของคุณ',
    'pdpa_desc' => 'เว็บไซต์นี้ใช้คุกกี้เพื่อประมวลผลการเข้าชม พัฒนาประสบการณ์การใช้งานให้ดียิ่งขึ้นตามพระราชบัญญัติคุ้มครองข้อมูลส่วนบุคคล (PDPA)',
    'pdpa_accept' => 'ยอมรับคุกกี้ทั้งหมด',
    'pdpa_reject' => 'ปฏิเสธคุกกี้ที่ไม่จำเป็น',
    'contact_us' => 'ติดต่อเรา',
    'address' => '123 ถ.วิทยาศาสตร์พัฒนา ต.ในเมือง อ.เมือง จ.ตาก 63000',
    'tel' => '055-123456',
    'privacy_policy' => 'นโยบายความเป็นส่วนตัว (Privacy Policy)',
    'terms_of_use' => 'ข้อกำหนดการใช้งาน',
    'search_placeholder' => 'ป้อนคำค้นหา (เช่น โครงสร้าง, O1, แผน)...',
    'oit_code' => 'รหัส OIT',
    'oit_title' => 'ชื่อตัวชี้วัด / หัวข้อเผยแพร่',
    'oit_download' => 'ลิงก์ / ช่องทางดาวน์โหลดข้อมูล',
    'oit_updated' => 'อัปเดตล่าสุด',
    'download_pdf' => 'ดาวน์โหลด PDF',
    'view_link' => 'ดูลิงก์ข้อมูล',
    'waiting_update' => 'รออัปเดตข้อมูล',
    'ita_showcase' => 'ศูนย์ข้อมูล ITA Online (OIT)',
    'ita_showcase_desc' => 'การประเมินคุณธรรมและความโปร่งใสในการดำเนินงานของสถานศึกษาออนไลน์ (Open Data Integrity and Transparency Assessment) ตามเกณฑ์ ป.ป.ช.',
    
    // About School Translations
    'about_school' => 'เกี่ยวกับโรงเรียน',
    'history' => 'ประวัติโรงเรียน',
    'vision_mission' => 'วิสัยทัศน์/พันธกิจ',
    'symbol' => 'ตราสัญลักษณ์',
    'colors' => 'สีประจำโรงเรียน',
    'song' => 'เพลงโรงเรียน',
    'executives' => 'ทำเนียบผู้บริหาร',
    'structure' => 'โครงสร้างการบริหาร',

    // Basic Info Translations
    'basic_info' => 'ข้อมูลพื้นฐานโรงเรียน',
    'cat_general_admin' => 'ข้อมูลทั่วไปและบริหาร',
    'cat_academic_schedule' => 'วิชาการและตารางเวลา',
    'cat_rules_handbook' => 'คู่มือและระเบียบปฏิบัติ',
    'cat_transparency_participation' => 'ความโปร่งใสและมีส่วนร่วม',
    'info_general' => 'ข้อมูลสารสนเทศ',
    'info_board' => 'คณะกรรมการสถานศึกษา',
    'info_charter' => 'ธรรมนูญโรงเรียน',
    'info_schedule_student' => 'ตารางเรียนนักเรียน',
    'info_schedule_teacher' => 'ตารางสอนครู',
    'info_handbook_student' => 'คู่มือนักเรียน',
    'info_student_list' => 'รายชื่อนักเรียน',
    'info_school_staff' => 'บุคลากรในโรงเรียน',
    'info_attendance_stats' => 'สถิติการมาเรียนประจำวัน',
    'info_discipline_rules' => 'ระเบียบวินัยและความประพฤติ',
    'info_dress_rules' => 'ระเบียบเครื่องแต่งกายและทรงผม',
    'info_support_handbook' => 'คู่มือระบบดูแลช่วยเหลือนักเรียน',
    'info_campus' => 'สหวิทยาเขตพระยาพิชัยดาบหัก',
    'info_feedback' => 'ช่องทางรับฟังความคิดเห็น',
    'info_complaints' => 'ช่องทางรับเรื่องร้องเรียน',
    'info_qna' => 'ถาม-ตอบ Q&A',
    'info_no_gift' => 'นโยบาย No Gift Policy',
    'info_dos_donts' => "แนวปฏิบัติ Do's and Don'ts",

    // School Dashboard Translations
    'info_dashboard_title' => 'ข้อมูลสารสนเทศโรงเรียน',
    'founded_date' => 'วันก่อตั้งโรงเรียน',
    'education_levels' => 'ระดับชั้นที่เปิดสอน',
    'location_address' => 'ที่ตั้งสถานศึกษา',
    'teacher_stats_title' => 'สถิติครูและบุคลากรทางการศึกษา',
    'student_stats_title' => 'สถิติจำนวนนักเรียนแยกตามห้องเรียนพิเศษ (ESC) และห้องเรียนปกติ',
    'academic_rank' => 'วิทยฐานะ',
    'personnel_count' => 'จำนวน (ราย)',
    'percentage' => 'ร้อยละ',
    'rank_assistant' => 'ครูผู้ช่วย',
    'rank_teacher1' => 'ครู ค.ศ. 1',
    'rank_level2' => 'ครู ค.ศ. 2 (ชำนาญการ)',
    'rank_level3' => 'ครู ค.ศ. 3 (ชำนาญการพิเศษ)',
    'rank_other' => 'บุคลากรอื่น ๆ',
    'total_personnel' => 'รวมบุคลากรทั้งหมด',
    'grade_level' => 'ระดับชั้น',
    'special_esc' => 'ห้องเรียนพิเศษ (ESC)',
    'regular_program' => 'ห้องเรียนปกติ',
    'total_students' => 'รวม (คน)',
    'total_students_overall' => 'รวมจำนวนนักเรียนทั้งหมด',
    'contact_coordinator' => 'ข้อมูลการติดต่อและประสานงาน',
    'phone_number' => 'เบอร์โทรศัพท์',
    'email_address' => 'อีเมล',
    'coordinator_name' => 'ผู้ประสานงาน',
];
