<?php
// config/lang_en.php
// Translation array for English language

return [
    'home' => 'Home',
    'ita' => 'ITA Online',
    'information_system' => 'Information Portals',
    'sgs' => 'SGS System (Grades)',
    'dmc' => 'DMC System (Students)',
    'obec' => 'OBEC Website',
    'emis' => 'EMIS Information System',
    'gpa' => 'GPA System (Binet)',
    'admin_panel' => 'Login',
    'admin_dashboard' => 'Admin Dashboard',
    'logout' => 'Logout',
    'welcome_school' => 'Welcome to our institution',
    'hero_title' => 'Driving Future with <br> <span class="text-gradient-primary">Innovation & Technology</span>',
    'hero_desc' => 'We focus on academic excellence, core values, and modern technology. We build trust through our transparent and accountable school management platform, ITA Online.',
    'check_ita' => 'Check ITA Online',
    'read_news' => 'Read News & PR',
    'slider1_title' => 'Computing and Innovation Hub',
    'slider1_desc' => 'Advanced computer labs and robotic kits designed for analysis and creation of scientific innovations.',
    'slider2_title' => 'Global Quality Educational Standard',
    'slider2_desc' => 'A bilingual curriculum promoting critical thinking, preparing students for success in the creative economy.',
    'ita_status' => 'Integrity & Transparency (ITA Online)',
    'ita_status_desc' => 'Annual performance reports and public documents index, evaluating indicators O1 - O43 for the current fiscal year.',
    'published_stats' => 'Published %d of %d indicators',
    'view_ita_table' => 'View Indicators',
    'external_portals' => 'External System Portals',
    'external_portals_desc' => 'Quick links to national educational systems for administration, teachers, and students.',
    'news_section_title' => 'School News & Press Release',
    'news_section_desc' => 'Latest events, official announcements, and public relations directly from the school.',
    'school_journal' => 'School Journal',
    'all' => 'All',
    'announcement' => 'Announcements',
    'activity' => 'Activities',
    'general' => 'General PR News',
    'no_news' => 'No school news published at this moment.',
    'read_more' => 'Read More',
    'by' => 'By',
    'pdpa_title' => 'We Value Your Privacy',
    'pdpa_desc' => 'This website uses cookies to analyze traffic and improve user experience, in compliance with the Personal Data Protection Act (PDPA).',
    'pdpa_accept' => 'Accept All Cookies',
    'pdpa_reject' => 'Reject Non-essential Cookies',
    'contact_us' => 'Contact Us',
    'address' => '123 Witthayasartpattana Rd., Nai Mueang, Mueang, Tak 63000',
    'tel' => '055-123456',
    'privacy_policy' => 'Privacy Policy',
    'terms_of_use' => 'Terms of Use',
    'search_placeholder' => 'Search indicators (e.g. Structure, O1, Plan)...',
    'oit_code' => 'OIT Code',
    'oit_title' => 'Indicator / Publication Topic',
    'oit_download' => 'Link / Document Download',
    'oit_updated' => 'Last Updated',
    'download_pdf' => 'Download PDF',
    'view_link' => 'View Source Link',
    'waiting_update' => 'Under Construction',
    'ita_showcase' => 'ITA Online Dashboard (OIT)',
    'ita_showcase_desc' => 'Open Data Integrity and Transparency Assessment for Educational Institutions under NACC guidelines.',
    
    // About School Translations
    'about_school' => 'About School',
    'history' => 'School History',
    'vision_mission' => 'Vision & Mission',
    'symbol' => 'School Symbols',
    'colors' => 'School Colors',
    'song' => 'School Song',
    'executives' => 'Executive Directory',
    'structure' => 'Administrative Structure',

    // Basic Info Translations
    'basic_info' => 'Basic Information',
    'cat_general_admin' => 'General & Administration',
    'cat_academic_schedule' => 'Academics & Schedules',
    'cat_rules_handbook' => 'Rules & Handbooks',
    'cat_transparency_participation' => 'Transparency & Feedback',
    'info_general' => 'School Information',
    'info_board' => 'School Board Committee',
    'info_charter' => 'School Charter',
    'info_schedule_student' => 'Student Class Schedule',
    'info_schedule_teacher' => 'Teacher Class Schedule',
    'info_handbook_student' => 'Student Handbook',
    'info_student_list' => 'Student Directory',
    'info_school_staff' => 'School Staff',
    'info_attendance_stats' => 'Daily Attendance Stats',
    'info_discipline_rules' => 'Student Conduct Rules',
    'info_dress_rules' => 'Uniform & Hair Rules',
    'info_support_handbook' => 'Student Support Handbook',
    'info_campus' => 'Phraya Phichai Campus',
    'info_feedback' => 'Feedback Channel',
    'info_complaints' => 'Complaint Channel',
    'info_qna' => 'Q&A Forum',
    'info_no_gift' => 'No Gift Policy',
    'info_dos_donts' => "Do's and Don'ts Guidelines",

    // School Dashboard Translations
    'info_dashboard_title' => 'School Information Dashboard',
    'founded_date' => 'Founded Date',
    'education_levels' => 'Education Levels Offered',
    'location_address' => 'School Location Address',
    'teacher_stats_title' => 'Educational Personnel & Teacher Statistics',
    'student_stats_title' => 'Student Enrollment by Special Program (ESC) and Regular Program',
    'academic_rank' => 'Academic Rank',
    'personnel_count' => 'Count (Persons)',
    'percentage' => 'Percentage',
    'rank_assistant' => 'Assistant Teacher',
    'rank_teacher1' => 'Teacher (K.S. 1)',
    'rank_level2' => 'Teacher (K.S. 2 / Professional)',
    'rank_level3' => 'Teacher (K.S. 3 / Senior Professional)',
    'rank_other' => 'Other Staff / Personnel',
    'total_personnel' => 'Total Personnel',
    'grade_level' => 'Grade Level',
    'special_esc' => 'Special Classroom (ESC)',
    'regular_program' => 'Regular Classroom',
    'total_students' => 'Total (Students)',
    'total_students_overall' => 'Total Enrollment',
    'contact_coordinator' => 'Contact Info & Coordination',
    'phone_number' => 'Telephone',
    'email_address' => 'Email',
    'coordinator_name' => 'Coordinator',
];
